-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Хост: 127.0.0.1:3306
-- Время создания: Янв 19 2022 г., 14:07
-- Версия сервера: 8.0.21
-- Версия PHP: 7.3.21

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- База данных: `recipe-blog`
--

-- --------------------------------------------------------

--
-- Структура таблицы `admin`
--

DROP TABLE IF EXISTS `admin`;
CREATE TABLE IF NOT EXISTS `admin` (
  `id_admin` int NOT NULL AUTO_INCREMENT,
  `login` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  PRIMARY KEY (`id_admin`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

--
-- Дамп данных таблицы `admin`
--

INSERT INTO `admin` (`id_admin`, `login`, `password`) VALUES
(1, 'admin', 'password');

-- --------------------------------------------------------

--
-- Структура таблицы `category`
--

DROP TABLE IF EXISTS `category`;
CREATE TABLE IF NOT EXISTS `category` (
  `id_category` int NOT NULL AUTO_INCREMENT,
  `name_category` varchar(255) NOT NULL,
  PRIMARY KEY (`id_category`)
) ENGINE=MyISAM AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

--
-- Дамп данных таблицы `category`
--

INSERT INTO `category` (`id_category`, `name_category`) VALUES
(1, 'cakes'),
(2, 'cookies'),
(3, 'cupcakes'),
(4, 'pies');

-- --------------------------------------------------------

--
-- Структура таблицы `recipe`
--

DROP TABLE IF EXISTS `recipe`;
CREATE TABLE IF NOT EXISTS `recipe` (
  `id_recipe` int NOT NULL AUTO_INCREMENT,
  `author` int NOT NULL,
  `title` varchar(255) NOT NULL,
  `photo` varchar(255) NOT NULL,
  `alt_photo` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `category` int NOT NULL,
  `prep_time` varchar(255) NOT NULL,
  `ingredients` text NOT NULL,
  `instructions` text NOT NULL,
  PRIMARY KEY (`id_recipe`)
) ENGINE=MyISAM AUTO_INCREMENT=31 DEFAULT CHARSET=utf8;

--
-- Дамп данных таблицы `recipe`
--

INSERT INTO `recipe` (`id_recipe`, `author`, `title`, `photo`, `alt_photo`, `description`, `category`, `prep_time`, `ingredients`, `instructions`) VALUES
(1, 1, 'No Bake White Chocolate Cheesecake', 'img/recipe01.jpg', 'Cheesecake', 'Sweet and beautifully creamy with just the right amount of salty, crunchy biscuit base, this No Bake White Chocolate Cheesecake is a fantastic dessert, perfect for Mother’s Day or even Easter Sunday. I’ve made no-bake cheesecakes before that need gelatine to set. Will this one set?\r\n \r\nThe beautiful thing about this cheesecake is that a perfect set is guaranteed because of the addition of the chocolate. In fact, I’d go as far as to say that you could even use this as a base for other no-bake cheesecakes. ', 1, '30 min', '100 g (1 stick) butter ;\r\n200 g (2 cups) crumbs digestive biscuits ;\r\n250 g (1¼ cups) white chocolate ;\r\n300 ml (1¼ cups) double (heavy) cream ;\r\n280 g (1¼ cups) full fat cream cheese ;\r\n1 teaspoon vanilla extract', 'Start by lining a 20cm (7 inch) spring form cake tin. Line the base and sides with non-stick paper. This makes removing the cheesecake easier. ;\r\nMelt the butter in a medium sized pan over a very low heat. ;\r\nUsing a food processor, blitz the biscuits until finely ground. ;\r\nAlternatively, place the biscuits in a food bag and crush with a rolling pin until you have fine crumbs. ;\r\nStir the crumbs into the melted butter mixing well to ensure all the crumbs are thoroughly covered. Press the buttery crumbs into the tin. Chill. ;\r\nMelt the chocolate in a bowl over a pan of simmering water ensuring the bottom of the bowl does not come into contact with the water. Allow to cool slightly.\r\nLightly whip the double cream until it forms soft peaks. ;\r\nBeat the vanilla extract into the cream cheese until smooth and shiny. ;\r\nBeat the melted chocolate into the cream cheese then fold in the whipped cream. ;\r\nPour the cheesecake mixture over the biscuit base and smooth the top. ;\r\nChill for at least two hours and preferably overnight.'),
(2, 1, 'Sticky Ginger Cake with Tangy Lemon Icing', 'img/recipe02.jpg', 'Ginger Cake', 'Ok, so I know that this is my second sweet recipe in a row, but I’ve been planning to post the recipe for this Sticky Ginger Cake with Lemon Drizzle Icing since last year and I can’t wait any longer! A year ago, this cake was on my list. But I got carried away posting so many other gorgeous autumn recipes such as my Old Fashioned Baked Rice Pudding and my Brandied Apple Custard, that before I knew it, Christmas was fast approaching, and I realised I had missed my moment.', 1, '1 h 30 min', '110 g butter ;\r\n110 g dark brown sugar ;\r\n210 g golden syrup (use maple syrup if golden syrup is not available) ;\r\n50 g treacle (or molasses) ;\r\n3-4 balls stem ginger diced small ;\r\n200 g oats ;\r\n135 g plain flour ;\r\n2 teaspoons baking powder ;\r\n½ teaspoon each mixed spice (cinnamon and ginger)', 'Pre heat the oven to 140°C (130°C fan)\r\nGrease and line a 20 x 23cm (7½ x 8½ inch) dish. ;\r\nPlace the wet ingredients into a small saucepan and heat gently until the butter has melted. Do not allow to simmer. ;\r\nCombine the dry ingredients.\r\nMix the wet ingredients into the dry ingredients then gently mix in the eggs and milk. ;\r\nPour into the baking dish, place in the oven and bake for 1h or until the cake springs back when you press the top.\r\nAllow to cool in the dish. ;\r\nThis cake gets moister and more gorgeous with time. If you can bare to, wrap it in foil and leave for up to a week before you eat it. ;\r\nBefore serving, mix the icing sugar with about ½ a tablespoon of lemon juice and drizzle over the cake. Sprinkle with some finely grated lemon zest.'),
(3, 1, 'Pecan Pie with Caramel Sprinkles', 'img/recipe03.jpg', 'Pecan Pie', 'Sweet, rich and caramelly, filled with creamy, soft pecans and topped with toasted, praline like nuts, this pecan pie is quick and easy to make. A gorgeous autumn dessert.\r\nI love pecan pie. I know it’s American and I’m British born and bred, but that bothers me not a jot. The crumbly flaky pastry filled with soft, creamy nuts encased in a sweet, rich, caramelly goo is gorgeous. The toasted, praline like pecans on the surface make the whole thing sing. This has to be one of my favourite autumn desserts.', 4, '55 min', 'Enough pastry to line a 23cm (9 inch) tart tin/pie dish ;\r\n60 g (¼ cup) melted butter ;\r\n300 g (1½ cups) soft light brown sugar\r\n2 tablespoons milk ;\r\n1 tablespoon flour ;\r\n1 teaspoon vanilla extract ;\r\n2 eggs ;\r\n110 g (1 cup) pecan halves', 'Line the tart tin in your usual way (I often use shop bought pastry for this) place in the fridge and chill for at least half an hour. ;\r\nMix together the butter sugar milk flour and vanilla extract. Stir in the eggs then stir in the pecan halves. ;\r\nPour the pecan mixture into the unbaked pastry case and bake at 180⁰C (350 F) for 45 minutes.'),
(4, 1, 'Peach Cobbler with Brandy', 'img/recipe04.jpg', 'Peach Cobbler', 'This morning I left Dan snoring in bed. It’s a Saturday and I love that lazy feeling where you wake up, check your alarm and realise that it’s 8 o’clock and that you have actually managed to sleep through your normal 6.30 am get up time. I spent the next half hour listening to the wind and the birds and thinking of something and nothing, coming in and out of sleep – my Saturday morning treat. This morning my thoughts morphed slowly from some photo’s I wanted to take of the garden, to my 4 year old nieces birthday to a peach cobbler I was eager to make. ', 2, '50 min', '6 peaches halved (stoned and sliced) ;\r\n40 g light brown sugar ;\r\n½ teaspoon vanilla extract ;\r\n1/8 teaspoon cinnamon ;\r\n175 g self raising flour (I use a mix of white and wholemeal) ;\r\n100 g butter from the fridge ;\r\n50 g light brown sugar ;\r\n40 g chopped nuts or seeds (I particularly like pecans or mixed seeds) ;\r\nPinch of salt ;\r\n5 tablespoons very cold water', 'Preheat the oven to 190°C. ;\r\nPut the peaches and vanilla sugar and cinnamon in the baking dish then toss together and place in the oven for 15 minutes. ;\r\nRub the butter into the flour using your fingertips. When all the butter is incorporated stir in the remaining ingredient. Now add the water slowly (as you may not need all of it) using your hands to bring the dough together into a ball. ;\r\nWhen the peaches have had their 15 minutes, remove them from the oven, give them a little stir and place balls of the dough on top of the peaches. I like to make about 12 small dough balls although 6 big ones works equally well. ;\r\nReturn the dish to the oven for 15 to 20 minutes. Cooking time will vary slightly depending on the size of the balls and each individual oven. When the balls are golden brown and peach juices are bubbling up at the side of them then remove the cobbler from the oven. Serve hot, warm or cold with cream or ice cream.'),
(5, 1, 'Healthier Low-Sugar Apple Crumble', 'img/recipe05.jpg', 'Apple Crumble', 'At this time of year, in my part of the world, there are apples everywhere. You only have to walk down the street and you will pass a box, basket or bag of them with a sign next to them urging you to help yourself. People are giving them away left, right and centre. Not having the pleasure of owning an apple tree myself, I am a very willing recipient of them.\r\nTo me, an apple cooking is the ubiquitous smell of autumn, and I often have something apple based in the fridge for most of the season. For some reason, each year I tend to hone in on one item. Some years it may be a pie, other years it’s apple butter, similar to apple sauce but more heavily spiced and cooked for much longer so that you end up with a smooth, dark, spicy spread that is gorgeous on bread or stirred into cake batters.', 4, '55 min', '4 medium sized cooking apples ;\r\n90 g granulated sugar ;\r\n½ teaspoon cinnamon ;\r\n2 tablespoons level flour ;\r\n75 g unsalted butter ;\r\n165 g plain flour (wholemeal or white your choice) ;\r\n55 g rolled oats ;\r\n110 g sugar ;\r\n70 g finely chopped nuts ;\r\n½ teaspoon cinnamon ;\r\nPinch of salt', 'Preheat the oven to 200°C ;\r\nPeel and core the apples then slice or dice to your preferred size (I go for about a 2cm square dice, if you prefer big chunks of apple cut them into larger chunks or thicker slices). Add the sugar and cinnamon, and the flour if you don’t want the apples to be too juicy. Stir together and place into your dish (see notes) pouring over any sugar cinnamon mixture that doesn’t cling to the apples. ;\r\nMelt the butter on the hob or in the microwave. ;\r\nMix the rest of the ingredients together then stir in the melted butter. ;\r\nNow stir in 50ml of cold water. The mixture should look clumpy and all the flour and oats should be damp. ;\r\nSprinkle the topping over the fruit then place in the oven and cook for 35-40 minutes. The topping should be golden and the apples soft and gently bubbling.'),
(6, 1, 'Chocolate Orange Cupcakes', 'img/recipe06.jpg', 'Chocolate Orange Cupcakes', 'These chocolate orange buns will be loved by kids and adults alike. They are quick, easy and impressive.\r\nLast weekend was one of our closest friend’s daughter’s first birthdays. Any first birthday deserves to be celebrated but here we had a special reason to party. This little girl has been through the mill in the past year. Born incredibly early she has been in and out of hospital since her arrival, has undergone surgery and spent many a day/week/month wired to machines and fed through tubes. Despite this I have never known a baby with such a ready, fantastic and infectious giggle.', 3, '40 min', '225 g butter ;\r\n175 g caster sugar ;\r\n50 g brown sugar ;\r\n4 eggs ;\r\n175 g self-raising flour ;\r\n50 g cocoa ;\r\n2 teaspoons baking powder ;\r\nZest of two oranges ;\r\n200 g icing sugar sieved ;\r\n150 g soft butter ;\r\n100 g plain chocolate ;\r\n1-2 tablespoons orange juice ;\r\n1 Terry’s Chocolate Orange', 'Preheat the oven to 170⁰C. ;\r\nBeat together the butter and sugar.\r\nBeat in the eggs one at a time adding a little of the flour if the mixture splits. ;\r\nSieve in the remaining dry ingredients, add the orange zest and stir together ensuring you do not over-beat the mixture. ;\r\nSpoon into the bun cases. ;\r\nBake for 20 minutes. Ensure the buns are fully cooked before you remove them. A skewer inserted into the center should come out clean. Alternatively, the bun should spring back when you press the top gently. ;\r\nMelt the chocolate. The easiest way to do this is to heat it gently in the microwave. I put it on rapid defrost and it takes about 1 minute. Make sure that you stir it every 15 seconds or so. This will aid the melting and ensure it doesn’t burn. ;\r\nWhilst the chocolate is cooling beat (or whisk if you dare) together the icing sugar, butter and orange juice or liqueur. ;\r\nAdd the cooled chocolate and beat together once more. ;\r\nOnce the buns have totally cooled place a small spoonful of the icing onto each bun pressing a segment of chocolate orange into each little mound of icing.'),
(7, 1, 'Classic German Cheesecake with Quark', 'img/recipe07.jpg', 'Cheesecake with Quark', 'If you’ve ever eaten cheesecake in Germany, you probably realized with the first bite that it’s a little different than cheesecakes made with cream cheese (like the New York cheesecake typically found in the United States).\r\nNope! It was more than likely made with Quark cheese, which is a staple component of traditional and authentic German cheesecake recipes.\r\nQuark is a fresh, creamy, un-aged cheese popular in Germany and elsewhere in Europe. It has a texture and consistency similar to Greek yogurt but it’s not tart like yogurt.', 1, '1 h 30 min', '4 egg whites ;\r\n3/4 Cup [400g] heavy cream ;\r\n4 1/2 Cups [1000g] Quark (plain) ;\r\n4 egg yolks ;\r\n3/4 Cup [150g] sugar ;\r\n1/4 Cup [50g] vanilla sugar ;\r\n1/2 Cup [70g] corn starch ;\r\n4 TBSP lemon juice ', 'Preheat oven to 350F/175C. ;\r\nBeat heavy cream to stiff peaks using a hand or stand mixer with the whisk attachment. Set aside. ;\r\nSeparate eggs and set egg yolks aside.\r\nBeat egg whites to stiff peaks using a hand or stand mixer with the whisk attachment. Set aside. ;\r\nAdd Quark, sugar, vanilla sugar, egg yolks, lemon juice, and corn starch to a medium sized mixing bowl. Stir to combine using a whisk. ;\r\nCarefully fold the heavy cream and then the egg whites into the batter. ;\r\nPour batter into a prepared springform pan. ;\r\nBake cheesecake for 60-70 minutes. If it starts turning too brown, cover with foil. ;\r\nTurn off oven, open the door a little, and let the cheesecake sit for another 10-15 minutes. '),
(8, 1, 'Easy German Lebkuchen Recipe', 'img/recipe08.jpg', 'German Lebkuchen', 'Often referred to as Germany’s version of gingerbread, Lebkuchen is a scrumptious baked treat that has become part of every German home’s Christmas tradition.\r\nThese soft, flourless cookies are filled with ground hazelnuts and almonds, candied citrus, and topped with chocolate or sugar glaze.\r\n\r\nIf you’re looking for an easy Nürnberger Elisenlebkuchen recipe, keep reading to learn how to make these delicious German iced gingerbread Christmas cookies. They’re a German Christmas favorite!', 2, '1 h', '2 TBSP cinnamon ;\r\n3/4 tsp cloves  ;\r\n1/2 tsp coriander  ;\r\n1/2 tsp cardamom ;\r\n1/2 tsp anise  ;\r\n1/2 tsp ginger ;\r\n1/4 nutmeg (or mace)  ;\r\n8 TBSP zest (5-7 lemons and 5-7 oranges) ; \r\n1 cup [198g] sugar ;\r\n3/4 cup [170ml] water ;\r\n1  1/2 cups [213g] whole almonds ;\r\n1  1/2 cups [213g] whole hazelnuts  ;\r\n1/2 cup (100g) brown sugar (lightly packed) ;\r\n1/4 tsp baking powder  ;\r\n1/8 tsp salt  ;\r\n1/2 cup [60g] candied zest   ;\r\n2 TBSP Lebkuchen Spice Mix  ;\r\n1/8 cup honey ;\r\n2 eggs', 'Combine the ground spices in a small bowl or jar. ;\r\nCover and set aside. ;\r\nThis recipe makes a little more spice mix than you need for these cookies. Feel free to add more spice mix to the cookies if you\'d like a stronger flavor. ;\r\nWash oranges and lemons. ;\r\nZest the citrus using a microplane. ;\r\nHeat water and sugar in a small saucepan over medium high heat. ;\r\nAdd zest and stir. ;\r\nBring to a low boil and simmer for 10 minutes. ;\r\nStrain out the liquid and let the candied zest cool in a small bowl. ;\r\nCover with plastic wrap and store in the fridge until you\'re ready to use it.\r\nThis recipe will likely make a little more candied zest than you need for these cookies. Feel free to add more if you\'d like a stronger flavor. ;\r\nUse a food processor to grind the almonds and hazelnuts until they\'re like crumbs. (But be careful that you don\'t grind so long that they turn into nut butter! It\'s ok if you have some larger nut chunks.They don\'t all have to be the same size.) Set ground nuts aside. ;\r\nAdd the brown sugar, Lebkuchen Spice Mix, baking powder, and salt to a mixing bowl (or the food processor or the bowl of a stand mixer). Mix with a whisk or spoon until combined'),
(9, 1, 'Simple Vanilla Cupcake Recipe', 'img/recipe09.jpg', 'Vanilla Cupcake', 'I mentioned a couple weeks ago that I’d be bringing you some new basic favorites and I started with my easy moist chocolate cake. Today, we are talking about these moist vanilla cupcakes and I’m pumped! One of the things that I’m always messing with is vanilla cake/cupcakes. It’s the never ending quest for all the best versions. I’m a believer that if you don’t have a good vanilla cake, you have NOTHING! Ok, dramatic, but it’s like the “tell”. If you don’t have a good vanilla, can anything else really be that good? There are so many ways to vary a vanilla cake and I want the best of all of them! I’m greedy like that. Plus, I know not every has the same idea of the perfect cupcake, so I like to have options.', 3, '30 min', '2 1/2 cups (325g) all purpose flour ;\r\n2 cups (414g) sugar ;\r\n3 tsp baking powder ;\r\n1 tsp salt ;\r\n1 cup (240ml) milk ;\r\n1/2 cup (120ml) vegetable oil ;\r\n1 tbsp vanilla extract ;\r\n2 large eggs ;\r\n1 cup (240ml) water ;\r\n1/2 cup (112g) salted butter, room temperature  ;\r\n1/2 cup (95g) shortening ;\r\n4 cups (460g) powdered sugar ;\r\n1 1/2 tsp vanilla extract ;\r\n2–3 tbsp (30-45ml) water or milk', 'Preheat oven to 350°F (176°C) and prepare a cupcake pan with liners. ;\r\nAdd the flour, sugar, baking powder and salt to a large mixer bowl and combine. Set aside. ;\r\nAdd the milk, vegetable oil, vanilla extract and eggs to a medium sized bowl and combine. ;\r\nAdd the wet ingredients to the dry ingredients and beat until well combined. ;\r\nSlowly add the water to the batter and mix on low speed until well combined. Scrape down the sides of the bowl as needed to make sure everything is well combined. Please note that the batter will be very thin. ;\r\nFill the cupcake liners about half way and bake for 15-17 minutes, or until a toothpick comes out with a few moist crumbs. ;\r\nRemove the cupcakes from oven and allow to cool for 2 minutes, then remove to a cooling rack to finish cooling. ;\r\nTo make the frosting, combine the butter and shortening in a large mixer bowl and mix until smooth. ;\r\nAdd 2 cups of powdered sugar and mix until smooth. ;\r\nAdd the vanilla extract and 1 tablespoon of water or milk and mix until smooth.\r\nAdd remaining powdered sugar and mix until smooth. ;\r\nAdd remaining water or milk as needed and mix until smooth. ;\r\nPipe the frosting onto the cupcakes. '),
(21, 1, 'Lemon Cheese Cake Classical Recipe', 'img/mockup2.jpg', 'Lemon Cheese Cake', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. \r\nExcepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 1, '55 min', 'fhfb ghrgh; hdsdfirgj; krrgoij; ksrjgi', 'fhiuerhvuihvtnijt; khvbqoghitohjpofthpoyjiyjhoifyjhjfhbvsjdbdsj j hvhkjdhd dg udg drughkdrjh; jhjdf iiudgfl seshf u ushfo dhg; ddfi udgg dsuifgis fg'),
(22, 1, 'Dark Chocolate Fondant', 'img/mockup3.jpg', 'Chocolate Fondant', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. \r\nDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 3, '1 h 30 min', 'Agfgdfgfgtg ;hd gfuig uihudf ug;sd fgysdgfui; dsyfg', 'Aghzrvkdfhfhgf    ;uydygf idgf;sdfg ;d fgisgdfui'),
(30, 1, 'Russian Strawberry Pancakes with Cream', 'img/mockup1.jpg', 'Russian Strawberry Pancakes', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 2, '45 min', 'Lorem Ipsum; Lorem Ipsum; Lorem Ipsum; Lorem Ipsum; Lorem Ipsum; Lorem Ipsum; Lorem Ipsum; Lorem Ipsum; Lorem Ipsum', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry ; Lorem Ipsum is simply dummy text of the printing and typesetting industry ; Lorem Ipsum is simply dummy text of the printing and typesetting industry ; Lorem Ipsum is simply dummy text of the printing and typesetting industry ; Lorem Ipsum is simply dummy text of the printing and typesetting industry ; Lorem Ipsum is simply dummy text of the printing and typesetting industry'),
(26, 1, 'Low Sugar Kiss with Raspberry Filling', 'img/mockup4.jpg', ' Kiss with Raspberry', 'srfgtt', 2, '1 h', 'rrgrgv;uhriuregi; uruhgiorg; irherjop; oirjoppkfes iejf orfj orf; rifhoeri fifi fprj fipefôzjo; rhfiorhjfb', 'jdfigj if; rrgrgv;uhriuregi; uruhgiorg; irherjop; oirjoppkfes iejf orfj orf; rifhoeri fifi fprj fipefôzjo; rhfiorhjfb'),
(28, 1, 'Peanut Cream Low Sugar Banana Pie', 'img/mockup5.jpg', 'Peanut Cream Banana Pie', '11111111111', 4, '1 h', '11111111; 11111111; 11111111; 11111111; 11111111; 11111111; 11111111; 11111111; 11111111; 11111111', 'dfcuihfkjrgfuerf; uegf oirhf ioefh ozifhzeiofgeoufgoeegf; uegfoiehfieuse uef ugefu efgeof; uegfoiezhf ugfiozehfi ehf; ejf fgfioe ; eufgozeu fefuhfoiez ; ufh ufhusdfdsfh dfihfg'),
(29, 1, 'Wonderful Blueberry Homemade Cheesecake', 'img/mockup6.jpg', 'Blueberry Cheesecake', 'Vhsjgfsukhfkjdrhgjkh11', 4, '55 min', 'Vhsjgfsukhfkjdrhgjkh;Vhsjgfsukhfkjdrhgjkh;Vhsjgfsukhfkjdrhgjkh;Vhsjgfsukhfkjdrhgjkh;Vhsjgfsukhfkjdrhgjkh;Vhsjgfsukhfkjdrhgjkh;Vhsjgfsukhfkjdrhgjkh', 'Vhsjgfsukhfkjdrhgjkh;Vhsjgfsukhfkjdrhgjkh;Vhsjgfsukhfkjdrhgjkh;Vhsjgfsukhfkjdrhgjkh;Vhsjgfsukhfkjdrhgjkh;Vhsjgfsukhfkjdrhgjkh;Vhsjgfsukhfkjdrhgjkh');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
